name: MSNGLNK
favicon: null
layout_spectrum: 0.535638279048726
typography_spectrum: 0.6544380772393197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242422'
    - '#fefefe'
    - '#acacac'
    - '#7c7c7c'
    - '#851216'
  brandStrength: 0.5960567109286785
  lightness: 0.03505351208150387
  saturation: 0.10537153598852456
  rhythmicContrast: 0.6853943825699389
purpose: []
